name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      # Install Ruby 3.x (required for Bundler 2.5.4)
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Specify Ruby 3.x or a specific version like '3.0.0'

      # Install Bundler and gems
      - name: Install Bundler
        run: gem install bundler -v 2.5.4

      - name: Install gems
        run: bundle install

      - name: Run Tests
        run: bundle exec fastlane unit_test
